a=int(input("Enter the 1st Denomination:"))
a1=int(input("Enter the 1st Denomination number of notes :"))
b=int(input("Enter the 2nd Denomination:"))
b1=int(input("Enter the 2nd Denomination number of notes :"))
c=int(input("Enter the 3rd Denomination:"))
c1=int(input("Enter the 3rd Denomination number of notes :"))
d=int(input("Enter the 4th Denomination:"))
d1=int(input("Enter the 4th Denomination number of notes :"))
x=((a*a1)+(b*b1)+(c*c1)+(d*d1))
print("Total Available balance in ATM :",x)
